import { useSession, getSession } from 'next-auth/react'
import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'

export default function Home() {
  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      // The user is not authenticated, handle it here.
      router.push('/home')
    }
  })

  if (status === 'loading') {
    console.log('Loading or not authenticated')
  }

  console.log('user is logged in')

  return (
    <div className="bg-[#F3F2EF] dark:bg-black dark:text-white h-screen overflow-y-scroll md:space-y-6">
      <Head>
        <title>Feed | LinkedIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex justify-center px-4 gap-x-5 sm:px-12">
        <div className="flex flex-col gap-5 md:flex-row">
          <Sidebar />
          <Feed />
        </div>
        {/* widget */}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  // Check if the user is authenticated on the server...
  const session = await getSession(context)
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: '/home'
      }
    }
  }

  return {
    props: { session }
  }
}
