import Head from 'next/head'
import { signOut } from 'next-auth/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={signOut}>Sign out</button>
    </div>
  )
}
